### ISSUE TITLE
Incorrect length

### ISSUE THREAD

**Issue by drsjb80** [msu-denver-cs/assignment-three-ErDiCooper#5]
SyntaxError (/private/tmp/assignment-three-ErDiCooper/app/models/car.rb:8: syntax error, unexpected in
  validates :model, length { in: 3..40}
                             ^~):
                             
diff --git a/app/models/car.rb b/app/models/car.rb
index 069f8e5..abcb768 100644
--- a/app/models/car.rb
+++ b/app/models/car.rb
@@ -5,5 +5,5 @@ class Car < ApplicationRecord
   validates_associated :parts
   
   validates :vin, length: { is: 17}
-  validates :model, length { in: 3..40}
+  validates :model, length: { in: 3..40}
 end

**Comment by ErDiCooper** [comment]
This has been addressed in the latest commit.
