### ISSUE TITLE
bad links

### ISSUE THREAD

**Issue by drsjb80** [msu-denver-cs/assignment-three-ErDiCooper#6]
diff --git a/app/views/cars/index.html.erb b/app/views/cars/index.html.erb
index bd0c21f..8de5199 100644
--- a/app/views/cars/index.html.erb
+++ b/app/views/cars/index.html.erb
@@ -2,9 +2,9 @@
 <p id="notice"><%= notice %></p>
 
 <tr>
-    <th><%= link_to "Cars", cars_path(index) %></th>
-    <th colspan="2"><%= link_to "Makes", makes_path(index) %></th>
-    <th colspan="3"><%= link_to "Parts", parts_path(index) %></th>
+    <th><%= link_to "Cars", cars_path%></th>
+    <th colspan="2"><%= link_to "Makes", makes_path%></th>
+    <th colspan="3"><%= link_to "Parts", parts_path%></th>
 </tr>

**Comment by ErDiCooper** [comment]
This has been addressed in the latest commit.
